-- returns CURRENT_TIMESTAMP at UTC
-- up
CREATE OR REPLACE FUNCTION now_utc() RETURNS TIMESTAMP WITHOUT TIME ZONE
AS
$$
BEGIN
  RETURN CURRENT_TIMESTAMP AT TIME ZONE 'UTC';
END;
$$
STABLE
STRICT
LANGUAGE plpgsql;


-- down
DROP FUNCTION now_utc();
----------
